#ifndef ESP32_OPENAI_ERROR_H
#define ESP32_OPENAI_ERROR_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    OPENAI_OK = 0,

    NEW_OPENAI_CLIENT_NULL_CLIENT = -1,
    NEW_OPENAI_CLIENT_NULL_TOKEN = -2,
    NEW_OPENAI_CLIENT_MALLOC = -3,

    OPENAI_CLIENT_FREE_NULL_CLIENT = -4,

    OPENAI_CLIENT_INIT_AUTH_NULL_CLIENT = -5,
    OPENAI_CLIENT_INIT_AUTH_ALREADY_INITIALIZED = -6,
    OPENAI_CLIENT_INIT_AUTH_NULL_TOKEN = -7,
    OPENAI_CLIENT_INIT_AUTH_MALLOC = -8,
    OPENAI_CLIENT_INIT_AUTH_SNPRINTF = -9,

    OPENAI_REQUEST_TO_JSON_NULL_REQUEST = -10,
    OPENAI_REQUEST_TO_JSON_NULL_REQ_JSON = -11,
    OPENAI_REQUEST_TO_JSON_NULL_MODEL_OR_INPUT = -12,
    OPENAI_REQUEST_TO_JSON_CREATE_OBJECT = -13,
    OPENAI_REQUEST_TO_JSON_ADD_MODEL = -14,
    OPENAI_REQUEST_TO_JSON_ADD_INPUT = -15,
    OPENAI_REQUEST_TO_JSON_PRINT = -16,

    OPENAI_RESPONSE_TO_CONTENT_NULL_RES_JSON = -17,
    OPENAI_RESPONSE_TO_CONTENT_NULL_RESPONSE = -18,
    OPENAI_RESPONSE_TO_CONTENT_PARSE_JSON = -19,
    OPENAI_RESPONSE_TO_CONTENT_NULL_OUTPUT = -20,
    OPENAI_RESPONSE_TO_CONTENT_NULL_OUTPUT_ITEM = -21,
    OPENAI_RESPONSE_TO_CONTENT_NULL_CONTENT = -22,
    OPENAI_RESPONSE_TO_CONTENT_NULL_CONTENT_ITEM = -23,
    OPENAI_RESPONSE_TO_CONTENT_NULL_TEXT = -24,
    OPENAI_RESPONSE_TO_CONTENT_INVALID_TEXT = -25,
    OPENAI_RESPONSE_TO_CONTENT_STRDUP = -26,

    OPENAI_CLIENT_CHAT_REQUEST_NULL_PARAMS = -27,
    OPENAI_CLIENT_CHAT_REQUEST_MALLOC = -28,
    OPENAI_CLIENT_CHAT_REQUEST_CURL_INIT = -29,
    OPENAI_CLIENT_CHAT_REQUEST_CURL_PERFORM = -30,
    OPENAI_CLIENT_CHAT_REQUEST_HTTP_ERROR = -31,
} OpenAIError;

const char* openai_error_to_string(OpenAIError error);

#ifdef __cplusplus
}
#endif

#endif // ESP32_OPENAI_ERROR_H